# Generated by Django 4.0 on 2021-12-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Sam', max_length=255),
            preserve_default=False,
        ),
    ]
