# Generated by Django 4.0 on 2021-12-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_type',
            new_name='type',
        ),
    ]
