# Generated by Django 4.0 on 2021-12-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_account_type_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='account_type',
        ),
    ]
