# Generated by Django 4.0 on 2021-12-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('trade', 'Trade')], max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('magazine', 'Magazine'), ('newsletter', 'Newsletter'), ('website', 'Website'), ('flag', 'Flag'), ('event', 'Event'), ('popup', 'Pop-Up'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('trade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('trade_contents', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='business.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
            ],
            bases=('business.product',),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/flag/')),
                ('months', models.PositiveIntegerField()),
                ('deployed', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('business.product',),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
                ('months', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('box', 'Box'), ('leaderboard', 'Leaderboard')], max_length=50)),
            ],
            bases=('business.product',),
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(max_length=255)),
            ],
            bases=('business.product',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
                ('media', models.ImageField(blank=True, null=True, upload_to='ads/website/')),
            ],
            bases=('business.product',),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.product')),
                ('size', models.CharField(choices=[('quarter', 'Quarter Page'), ('half', 'Half Page'), ('full', 'Full Page'), ('two', 'Two Page Spread')], max_length=255)),
                ('placement', models.CharField(choices=[('inside_front', 'Inside Front Cover'), ('opposite_inside_front', 'Opposite Inside Front Cover'), ('inside_back', 'Inside Back Cover'), ('opposite_inside_back', 'Opposite Inside Back Cover'), ('back', 'Back Cover'), ('two_page_centerfold', 'Two Page Centerfold Spread')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/magazine/')),
                ('is_color', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.issue')),
            ],
            bases=('business.product',),
        ),
    ]
