# Generated by Django 4.0 on 2021-12-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_type_user_account_type'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('trade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('trade_contents', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('trade', 'Trade')], max_length=50)),
                ('status', models.CharField(choices=[(1, 'Created'), (2, 'Pending'), (3, 'Confirmed'), (4, 'Cancelled')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='company',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='issue',
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
                ('size', models.CharField(choices=[(1, 'Quarter Page'), (2, 'Half Page'), (3, 'Full Page'), (4, 'Two Page Spread')], max_length=1)),
                ('placement', models.CharField(choices=[(1, 'Inside Front Cover'), (2, 'Opposite Inside Front Cover'), (3, 'Inside Back Cover'), (4, 'Opposite Inside Back Cover'), (5, 'Back Cover'), (6, 'Two Page Centerfold Spread')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('is_color', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.issue')),
            ],
            bases=('business.advertisement',),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='business.contract'),
        ),
    ]
