# Generated by Django 4.0 on 2021-12-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
