# Generated by Django 4.0 on 2021-12-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_deal_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='is_hidden',
            new_name='is_private',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='value',
        ),
    ]
