# Generated by Django 4.0 on 2021-12-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_advertisement_contract_remove_deal_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
            ],
            bases=('business.advertisement',),
        ),
    ]
