# Generated by Django 4.0 on 2021-12-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_is_hidden_deal_is_private_remove_deal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contract',
            new_name='deal',
        ),
    ]
