# Generated by Django 4.0 on 2021-12-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='placement',
            field=models.CharField(choices=[('inside_front', 'Inside Front Cover'), ('opposite_inside_front', 'Opposite Inside Front Cover'), ('inside_back', 'Inside Back Cover'), ('opposite_inside_back', 'Opposite Inside Back Cover'), ('back', 'Back Cover'), ('two_page_centerfold', 'Two Page Centerfold Spread')], max_length=255),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='size',
            field=models.CharField(choices=[('quarter', 'Quarter Page'), ('half', 'Half Page'), ('full', 'Full Page'), ('two', 'Two Page Spread')], max_length=255),
        ),
    ]
