# Generated by Django 4.0 on 2021-12-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_contract_status_alter_magazine_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('magazine', 'Magazine'), ('newsletter', 'Newsletter'), ('website', 'Website'), ('flag', 'Flag'), ('event', 'Event'), ('popup', 'Pop-Up'), ('other', 'Other')], default='website', max_length=50),
            preserve_default=False,
        ),
    ]
