# Generated by Django 4.0 on 2021-12-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_product_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
