# Generated by Django 4.0 on 2021-12-17 04:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_advertisement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
            ],
            bases=('business.advertisement',),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/flag/')),
                ('months', models.PositiveIntegerField()),
                ('deployed', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('business.advertisement',),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
                ('months', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('box', 'Box'), ('leaderboard', 'Leaderboard')], max_length=50)),
            ],
            bases=('business.advertisement',),
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.advertisement')),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(max_length=255)),
            ],
            bases=('business.advertisement',),
        ),
        migrations.RemoveField(
            model_name='website',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='ads/website/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/magazine/'),
        ),
    ]
