# Generated by Django 4.0 on 2021-12-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_event_flag_newsletter_popup_remove_website_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
