# Generated by Django 4.0 on 2021-12-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cash_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trade_contents',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trade_value',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='trade_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='trade_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
