# Generated by Django 4.0 on 2021-12-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_rename_cash_value_product_value_remove_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.deal'),
        ),
    ]
