# Generated by Django 4.0 on 2021-12-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('magazine', 'Magazine'), ('newsletter', 'Newsletter'), ('website', 'Website'), ('flag', 'Flag'), ('event', 'Event'), ('popup', 'Pop-Up'), ('other', 'Other')], default='magazine', max_length=50),
            preserve_default=False,
        ),
    ]
