# Generated by Django 4.0 on 2021-12-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='deployed',
        ),
    ]
