# Generated by Django 4.0 on 2021-12-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_flag_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal',
            field=models.ForeignKey(help_text='Enter cash value of this product in $', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.deal'),
        ),
    ]
