# Generated by Django 4.0 on 2021-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_product_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='deals/'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/flag/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/magazine/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='products/website/'),
        ),
    ]
