# Generated by Django 4.0 on 2021-12-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_deal_pdf_alter_flag_image_alter_magazine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='business.company'),
        ),
    ]
