# Generated by Django 4.0 on 2021-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_deal_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.CharField(default='samsuchin@college.harvard.edu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(default='Sam Suchin Contact', max_length=255),
            preserve_default=False,
        ),
    ]
