# Generated by Django 4.0 on 2022-01-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_company_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='notes',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='trade_information',
        ),
        migrations.AddField(
            model_name='deal',
            name='cash_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Discount Percentage'),
        ),
    ]
