# Generated by Django 4.0 on 2022-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_rename_notes_deal_info_remove_deal_trade_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_address',
            field=models.CharField(default='44 bow street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='city_state_zip',
            field=models.CharField(default='Cambridge, MA 02138', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(default='999 999 9999', max_length=255),
            preserve_default=False,
        ),
    ]
