# Generated by Django 4.0 on 2022-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_company_billing_address_company_city_state_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
