# Generated by Django 4.0 on 2022-01-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_company_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Discount Percentage'),
        ),
    ]
