# Generated by Django 4.0 on 2022-02-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('business', '0021_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
