# Generated by Django 4.0 on 2021-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
