# Generated by Django 4.0 on 2021-12-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0003_alter_apiclient_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='authorization_code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='refresh_token',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
